[pytest]
testpaths = .
python_files = test_app.py
addopts =
    --cov=.
    --cov-report=term-missing
    --cov-report=lcov:coverage.lcov
    --cov-fail-under=75
    -v

[coverage:run]
omit =
    test_app.py
    make_requests.py