sonar.projectKey=cybersec-api-python
sonar.projectName=CyberSec API (Python)
sonar.sources=.
sonar.inclusions=App.py
sonar.tests=.
sonar.test.inclusions=test_app.py
sonar.python.coverage.reportPaths=coverage.lcov
sonar.exclusions=**/__pycache__/**,**/*.pyc
