sonar.projectKey=cybersec-api-python
sonar.projectName=CyberSec API (Python)
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.lcov
sonar.exclusions=**/__pycache__/**,**/*.pyc